// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'location_models.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SavedLocationResponse _$SavedLocationResponseFromJson(
  Map<String, dynamic> json,
) => SavedLocationResponse(
  id: (json['id'] as num).toInt(),
  userId: (json['user_id'] as num?)?.toInt(),
  name: json['name'] as String,
  latitude: (json['latitude'] as num).toDouble(),
  longitude: (json['longitude'] as num).toDouble(),
  managementCompanyId: json['management_company_id'] as String?,
  boilerHouseId: (json['boiler_house_id'] as num?)?.toInt(),
  floors: (json['floors'] as num?)?.toInt(),
  residentsCount: (json['residents_count'] as num?)?.toInt(),
  rooms: (json['rooms'] as num?)?.toInt(),
  totalArea: (json['total_area'] as num?)?.toDouble(),
  yearBuilt: (json['year_built'] as num?)?.toInt(),
  fiasHouseGuid: json['fias_house_guid'] as String?,
  fiasAOGuid: json['fias_a_o_guid'] as String?,
  locationUUID: json['location_u_u_i_d'] as String?,
  providesHeating: json['provides_heating'] as bool?,
  providesHotWater: json['provides_hot_water'] as bool?,
  cadastralNumber: json['cadastral_number'] as String?,
  commissioningDate: json['commissioning_date'] as String?,
  managementCompanyName: json['management_company_name'] as String?,
  accountsCount: (json['accounts_count'] as num?)?.toInt(),
  stoveType: json['stove_type'] as String?,
  housingType: json['housing_type'] as String?,
  entrancesCount: (json['entrances_count'] as num?)?.toInt(),
  gisOktmo: json['gis_oktmo'] as String?,
  gisState: json['gis_state'] as String?,
  gisLifecycleStage: json['gis_lifecycle_stage'] as String?,
  undergroundFloors: (json['underground_floors'] as num?)?.toInt(),
  gisTimezone: json['gis_timezone'] as String?,
  gisCulturalHeritage: json['gis_cultural_heritage'] as bool?,
  gisFederalProperty: json['gis_federal_property'] as bool?,
  gisMunicipalProperty: json['gis_municipal_property'] as bool?,
  gisHostelType: json['gis_hostel_type'] as String?,
  gisStatus: json['gis_status'] as String?,
  createdAt: json['created_at'] as String,
  updatedAt: json['updated_at'] as String?,
  photos: (json['photos'] as List<dynamic>?)
      ?.map((e) => PhotoInfo.fromJson(e as Map<String, dynamic>))
      .toList(),
  accounts: (json['accounts'] as List<dynamic>?)
      ?.map((e) => AccountResponse.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$SavedLocationResponseToJson(
  SavedLocationResponse instance,
) => <String, dynamic>{
  'id': instance.id,
  'user_id': instance.userId,
  'name': instance.name,
  'latitude': instance.latitude,
  'longitude': instance.longitude,
  'management_company_id': instance.managementCompanyId,
  'boiler_house_id': instance.boilerHouseId,
  'floors': instance.floors,
  'residents_count': instance.residentsCount,
  'rooms': instance.rooms,
  'total_area': instance.totalArea,
  'year_built': instance.yearBuilt,
  'fias_house_guid': instance.fiasHouseGuid,
  'fias_a_o_guid': instance.fiasAOGuid,
  'location_u_u_i_d': instance.locationUUID,
  'provides_heating': instance.providesHeating,
  'provides_hot_water': instance.providesHotWater,
  'cadastral_number': instance.cadastralNumber,
  'commissioning_date': instance.commissioningDate,
  'management_company_name': instance.managementCompanyName,
  'accounts_count': instance.accountsCount,
  'stove_type': instance.stoveType,
  'housing_type': instance.housingType,
  'entrances_count': instance.entrancesCount,
  'gis_oktmo': instance.gisOktmo,
  'gis_state': instance.gisState,
  'gis_lifecycle_stage': instance.gisLifecycleStage,
  'underground_floors': instance.undergroundFloors,
  'gis_timezone': instance.gisTimezone,
  'gis_cultural_heritage': instance.gisCulturalHeritage,
  'gis_federal_property': instance.gisFederalProperty,
  'gis_municipal_property': instance.gisMunicipalProperty,
  'gis_hostel_type': instance.gisHostelType,
  'gis_status': instance.gisStatus,
  'created_at': instance.createdAt,
  'updated_at': instance.updatedAt,
  'photos': instance.photos,
  'accounts': instance.accounts,
};

SavedLocationCreate _$SavedLocationCreateFromJson(Map<String, dynamic> json) =>
    SavedLocationCreate(
      name: json['name'] as String,
      latitude: (json['latitude'] as num).toDouble(),
      longitude: (json['longitude'] as num).toDouble(),
      managementCompanyId: json['management_company_id'] as String?,
      boilerHouseId: (json['boiler_house_id'] as num?)?.toInt(),
      floors: (json['floors'] as num?)?.toInt(),
      residentsCount: (json['residents_count'] as num?)?.toInt(),
      rooms: (json['rooms'] as num?)?.toInt(),
      totalArea: (json['total_area'] as num?)?.toDouble(),
      yearBuilt: (json['year_built'] as num?)?.toInt(),
      fiasHouseGuid: json['fias_house_guid'] as String?,
      fiasAOGuid: json['fias_a_o_guid'] as String?,
      locationUUID: json['location_u_u_i_d'] as String?,
      providesHeating: json['provides_heating'] as bool?,
      providesHotWater: json['provides_hot_water'] as bool?,
      cadastralNumber: json['cadastral_number'] as String?,
      commissioningDate: json['commissioning_date'] as String?,
      stoveType: json['stove_type'] as String?,
      housingType: json['housing_type'] as String?,
      entrancesCount: (json['entrances_count'] as num?)?.toInt(),
      gisOktmo: json['gis_oktmo'] as String?,
      gisState: json['gis_state'] as String?,
      gisLifecycleStage: json['gis_lifecycle_stage'] as String?,
      undergroundFloors: (json['underground_floors'] as num?)?.toInt(),
      gisTimezone: json['gis_timezone'] as String?,
      gisCulturalHeritage: json['gis_cultural_heritage'] as bool?,
      gisFederalProperty: json['gis_federal_property'] as bool?,
      gisMunicipalProperty: json['gis_municipal_property'] as bool?,
      gisHostelType: json['gis_hostel_type'] as String?,
      gisStatus: json['gis_status'] as String?,
    );

Map<String, dynamic> _$SavedLocationCreateToJson(
  SavedLocationCreate instance,
) => <String, dynamic>{
  'name': instance.name,
  'latitude': instance.latitude,
  'longitude': instance.longitude,
  'management_company_id': instance.managementCompanyId,
  'boiler_house_id': instance.boilerHouseId,
  'floors': instance.floors,
  'residents_count': instance.residentsCount,
  'rooms': instance.rooms,
  'total_area': instance.totalArea,
  'year_built': instance.yearBuilt,
  'fias_house_guid': instance.fiasHouseGuid,
  'fias_a_o_guid': instance.fiasAOGuid,
  'location_u_u_i_d': instance.locationUUID,
  'provides_heating': instance.providesHeating,
  'provides_hot_water': instance.providesHotWater,
  'cadastral_number': instance.cadastralNumber,
  'commissioning_date': instance.commissioningDate,
  'stove_type': instance.stoveType,
  'housing_type': instance.housingType,
  'entrances_count': instance.entrancesCount,
  'gis_oktmo': instance.gisOktmo,
  'gis_state': instance.gisState,
  'gis_lifecycle_stage': instance.gisLifecycleStage,
  'underground_floors': instance.undergroundFloors,
  'gis_timezone': instance.gisTimezone,
  'gis_cultural_heritage': instance.gisCulturalHeritage,
  'gis_federal_property': instance.gisFederalProperty,
  'gis_municipal_property': instance.gisMunicipalProperty,
  'gis_hostel_type': instance.gisHostelType,
  'gis_status': instance.gisStatus,
};

SavedLocationUpdate _$SavedLocationUpdateFromJson(Map<String, dynamic> json) =>
    SavedLocationUpdate(
      name: json['name'] as String?,
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      managementCompanyId: json['management_company_id'] as String?,
      boilerHouseId: (json['boiler_house_id'] as num?)?.toInt(),
      floors: (json['floors'] as num?)?.toInt(),
      residentsCount: (json['residents_count'] as num?)?.toInt(),
      rooms: (json['rooms'] as num?)?.toInt(),
      totalArea: (json['total_area'] as num?)?.toDouble(),
      yearBuilt: (json['year_built'] as num?)?.toInt(),
      fiasHouseGuid: json['fias_house_guid'] as String?,
      fiasAOGuid: json['fias_a_o_guid'] as String?,
      locationUUID: json['location_u_u_i_d'] as String?,
      providesHeating: json['provides_heating'] as bool?,
      providesHotWater: json['provides_hot_water'] as bool?,
      cadastralNumber: json['cadastral_number'] as String?,
      commissioningDate: json['commissioning_date'] as String?,
      stoveType: json['stove_type'] as String?,
      housingType: json['housing_type'] as String?,
      entrancesCount: (json['entrances_count'] as num?)?.toInt(),
      gisOktmo: json['gis_oktmo'] as String?,
      gisState: json['gis_state'] as String?,
      gisLifecycleStage: json['gis_lifecycle_stage'] as String?,
      undergroundFloors: (json['underground_floors'] as num?)?.toInt(),
      gisTimezone: json['gis_timezone'] as String?,
      gisCulturalHeritage: json['gis_cultural_heritage'] as bool?,
      gisFederalProperty: json['gis_federal_property'] as bool?,
      gisMunicipalProperty: json['gis_municipal_property'] as bool?,
      gisHostelType: json['gis_hostel_type'] as String?,
      gisStatus: json['gis_status'] as String?,
    );

Map<String, dynamic> _$SavedLocationUpdateToJson(
  SavedLocationUpdate instance,
) => <String, dynamic>{
  'name': ?instance.name,
  'latitude': ?instance.latitude,
  'longitude': ?instance.longitude,
  'management_company_id': ?instance.managementCompanyId,
  'boiler_house_id': ?instance.boilerHouseId,
  'floors': ?instance.floors,
  'residents_count': ?instance.residentsCount,
  'rooms': ?instance.rooms,
  'total_area': ?instance.totalArea,
  'year_built': ?instance.yearBuilt,
  'fias_house_guid': ?instance.fiasHouseGuid,
  'fias_a_o_guid': ?instance.fiasAOGuid,
  'location_u_u_i_d': ?instance.locationUUID,
  'provides_heating': ?instance.providesHeating,
  'provides_hot_water': ?instance.providesHotWater,
  'cadastral_number': ?instance.cadastralNumber,
  'commissioning_date': ?instance.commissioningDate,
  'stove_type': ?instance.stoveType,
  'housing_type': ?instance.housingType,
  'entrances_count': ?instance.entrancesCount,
  'gis_oktmo': ?instance.gisOktmo,
  'gis_state': ?instance.gisState,
  'gis_lifecycle_stage': ?instance.gisLifecycleStage,
  'underground_floors': ?instance.undergroundFloors,
  'gis_timezone': ?instance.gisTimezone,
  'gis_cultural_heritage': ?instance.gisCulturalHeritage,
  'gis_federal_property': ?instance.gisFederalProperty,
  'gis_municipal_property': ?instance.gisMunicipalProperty,
  'gis_hostel_type': ?instance.gisHostelType,
  'gis_status': ?instance.gisStatus,
};

AccountResponse _$AccountResponseFromJson(Map<String, dynamic> json) =>
    AccountResponse(
      id: (json['id'] as num).toInt(),
      locationId: (json['location_id'] as num?)?.toInt(),
      accountNumber: json['account_number'] as String,
      address: json['address'] as String?,
      fio: json['fio'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      area: (json['area'] as num?)?.toDouble(),
      serviceType: json['service_type'] as String?,
      status: json['status'] as String?,
      jkuIdentifier: json['jku_identifier'] as String?,
      openDate: json['open_date'] as String?,
      closeDate: json['close_date'] as String?,
      cadastralNumber: json['cadastral_number'] as String?,
      roomsCount: (json['rooms_count'] as num?)?.toInt(),
      gisEls: json['gis_els'] as String?,
      gisAccountType: json['gis_account_type'] as String?,
      gisIsTenant: json['gis_is_tenant'] as bool?,
      gisIsSplit: json['gis_is_split'] as bool?,
      gisLastName: json['gis_last_name'] as String?,
      gisFirstName: json['gis_first_name'] as String?,
      gisMiddleName: json['gis_middle_name'] as String?,
      gisSnils: json['gis_snils'] as String?,
      gisDocType: json['gis_doc_type'] as String?,
      gisDocNumber: json['gis_doc_number'] as String?,
      gisDocSeries: json['gis_doc_series'] as String?,
      gisDocDate: json['gis_doc_date'] as String?,
      gisOgrn: json['gis_ogrn'] as String?,
      gisNza: json['gis_nza'] as String?,
      gisKpp: json['gis_kpp'] as String?,
      livingArea: (json['living_area'] as num?)?.toDouble(),
      heatedArea: (json['heated_area'] as num?)?.toDouble(),
      residentsCount: (json['residents_count'] as num?)?.toInt(),
      gisPremisesType: json['gis_premises_type'] as String?,
      gisPremisesNumber: json['gis_premises_number'] as String?,
      gisRoomNumber: json['gis_room_number'] as String?,
      gisPaymentShare: (json['gis_payment_share'] as num?)?.toDouble(),
      gisEgrpConditionalNumber: json['gis_egrp_conditional_number'] as String?,
      gisEgrpRegistrationNumber:
          json['gis_egrp_registration_number'] as String?,
      gisEgrpRegistrationDate: json['gis_egrp_registration_date'] as String?,
      gisStatus: json['gis_status'] as String?,
      createdAt: json['created_at'] as String,
      updatedAt: json['updated_at'] as String?,
      locationUUID: json['location_u_u_i_d'] as String?,
    );

Map<String, dynamic> _$AccountResponseToJson(AccountResponse instance) =>
    <String, dynamic>{
      'id': instance.id,
      'location_id': instance.locationId,
      'account_number': instance.accountNumber,
      'address': instance.address,
      'fio': instance.fio,
      'phone': instance.phone,
      'email': instance.email,
      'area': instance.area,
      'service_type': instance.serviceType,
      'status': instance.status,
      'jku_identifier': instance.jkuIdentifier,
      'open_date': instance.openDate,
      'close_date': instance.closeDate,
      'cadastral_number': instance.cadastralNumber,
      'rooms_count': instance.roomsCount,
      'gis_els': instance.gisEls,
      'gis_account_type': instance.gisAccountType,
      'gis_is_tenant': instance.gisIsTenant,
      'gis_is_split': instance.gisIsSplit,
      'gis_last_name': instance.gisLastName,
      'gis_first_name': instance.gisFirstName,
      'gis_middle_name': instance.gisMiddleName,
      'gis_snils': instance.gisSnils,
      'gis_doc_type': instance.gisDocType,
      'gis_doc_number': instance.gisDocNumber,
      'gis_doc_series': instance.gisDocSeries,
      'gis_doc_date': instance.gisDocDate,
      'gis_ogrn': instance.gisOgrn,
      'gis_nza': instance.gisNza,
      'gis_kpp': instance.gisKpp,
      'living_area': instance.livingArea,
      'heated_area': instance.heatedArea,
      'residents_count': instance.residentsCount,
      'gis_premises_type': instance.gisPremisesType,
      'gis_premises_number': instance.gisPremisesNumber,
      'gis_room_number': instance.gisRoomNumber,
      'gis_payment_share': instance.gisPaymentShare,
      'gis_egrp_conditional_number': instance.gisEgrpConditionalNumber,
      'gis_egrp_registration_number': instance.gisEgrpRegistrationNumber,
      'gis_egrp_registration_date': instance.gisEgrpRegistrationDate,
      'gis_status': instance.gisStatus,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'location_u_u_i_d': instance.locationUUID,
    };

AccountCreate _$AccountCreateFromJson(Map<String, dynamic> json) =>
    AccountCreate(
      locationId: (json['location_id'] as num).toInt(),
      accountNumber: json['account_number'] as String,
      address: json['address'] as String?,
      fio: json['fio'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      area: (json['area'] as num?)?.toDouble(),
      serviceType: json['service_type'] as String?,
      status: json['status'] as String?,
      jkuIdentifier: json['jku_identifier'] as String?,
      openDate: json['open_date'] as String?,
      closeDate: json['close_date'] as String?,
      cadastralNumber: json['cadastral_number'] as String?,
      roomsCount: (json['rooms_count'] as num?)?.toInt(),
    );

Map<String, dynamic> _$AccountCreateToJson(AccountCreate instance) =>
    <String, dynamic>{
      'location_id': instance.locationId,
      'account_number': instance.accountNumber,
      'address': instance.address,
      'fio': instance.fio,
      'phone': instance.phone,
      'email': instance.email,
      'area': instance.area,
      'service_type': instance.serviceType,
      'status': instance.status,
      'jku_identifier': instance.jkuIdentifier,
      'open_date': instance.openDate,
      'close_date': instance.closeDate,
      'cadastral_number': instance.cadastralNumber,
      'rooms_count': instance.roomsCount,
    };

AccountUpdate _$AccountUpdateFromJson(Map<String, dynamic> json) =>
    AccountUpdate(
      locationId: (json['location_id'] as num?)?.toInt(),
      accountNumber: json['account_number'] as String?,
      address: json['address'] as String?,
      fio: json['fio'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      area: (json['area'] as num?)?.toDouble(),
      serviceType: json['service_type'] as String?,
      status: json['status'] as String?,
      jkuIdentifier: json['jku_identifier'] as String?,
      openDate: json['open_date'] as String?,
      closeDate: json['close_date'] as String?,
      cadastralNumber: json['cadastral_number'] as String?,
      roomsCount: (json['rooms_count'] as num?)?.toInt(),
      gisEls: json['gis_els'] as String?,
      gisAccountType: json['gis_account_type'] as String?,
      gisIsTenant: json['gis_is_tenant'] as bool?,
      gisIsSplit: json['gis_is_split'] as bool?,
      gisLastName: json['gis_last_name'] as String?,
      gisFirstName: json['gis_first_name'] as String?,
      gisMiddleName: json['gis_middle_name'] as String?,
      gisSnils: json['gis_snils'] as String?,
      gisDocType: json['gis_doc_type'] as String?,
      gisDocNumber: json['gis_doc_number'] as String?,
      gisDocSeries: json['gis_doc_series'] as String?,
      gisDocDate: json['gis_doc_date'] as String?,
      gisOgrn: json['gis_ogrn'] as String?,
      gisNza: json['gis_nza'] as String?,
      gisKpp: json['gis_kpp'] as String?,
      livingArea: (json['living_area'] as num?)?.toDouble(),
      heatedArea: (json['heated_area'] as num?)?.toDouble(),
      residentsCount: (json['residents_count'] as num?)?.toInt(),
      gisPremisesType: json['gis_premises_type'] as String?,
      gisPremisesNumber: json['gis_premises_number'] as String?,
      gisRoomNumber: json['gis_room_number'] as String?,
      gisPaymentShare: (json['gis_payment_share'] as num?)?.toDouble(),
      gisEgrpConditionalNumber: json['gis_egrp_conditional_number'] as String?,
      gisEgrpRegistrationNumber:
          json['gis_egrp_registration_number'] as String?,
      gisEgrpRegistrationDate: json['gis_egrp_registration_date'] as String?,
    );

Map<String, dynamic> _$AccountUpdateToJson(AccountUpdate instance) =>
    <String, dynamic>{
      'location_id': ?instance.locationId,
      'account_number': ?instance.accountNumber,
      'address': ?instance.address,
      'fio': ?instance.fio,
      'phone': ?instance.phone,
      'email': ?instance.email,
      'area': ?instance.area,
      'service_type': ?instance.serviceType,
      'status': ?instance.status,
      'jku_identifier': ?instance.jkuIdentifier,
      'open_date': ?instance.openDate,
      'close_date': ?instance.closeDate,
      'cadastral_number': ?instance.cadastralNumber,
      'rooms_count': ?instance.roomsCount,
      'gis_els': ?instance.gisEls,
      'gis_account_type': ?instance.gisAccountType,
      'gis_is_tenant': ?instance.gisIsTenant,
      'gis_is_split': ?instance.gisIsSplit,
      'gis_last_name': ?instance.gisLastName,
      'gis_first_name': ?instance.gisFirstName,
      'gis_middle_name': ?instance.gisMiddleName,
      'gis_snils': ?instance.gisSnils,
      'gis_doc_type': ?instance.gisDocType,
      'gis_doc_number': ?instance.gisDocNumber,
      'gis_doc_series': ?instance.gisDocSeries,
      'gis_doc_date': ?instance.gisDocDate,
      'gis_ogrn': ?instance.gisOgrn,
      'gis_nza': ?instance.gisNza,
      'gis_kpp': ?instance.gisKpp,
      'living_area': ?instance.livingArea,
      'heated_area': ?instance.heatedArea,
      'residents_count': ?instance.residentsCount,
      'gis_premises_type': ?instance.gisPremisesType,
      'gis_premises_number': ?instance.gisPremisesNumber,
      'gis_room_number': ?instance.gisRoomNumber,
      'gis_payment_share': ?instance.gisPaymentShare,
      'gis_egrp_conditional_number': ?instance.gisEgrpConditionalNumber,
      'gis_egrp_registration_number': ?instance.gisEgrpRegistrationNumber,
      'gis_egrp_registration_date': ?instance.gisEgrpRegistrationDate,
    };
